#pragma config(Motor,  port2,           frontRight,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           backRight,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           frontLeft,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port5,           backLeft,      tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port6,           goal,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           coneLeft,      tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){

	while(1 == 1)
		{
			/* mecanum drivetrain, joystick arcade control */
			motor[frontRight] = - vexRT[AccelY] - vexRT[AccelX] - vexRT[Ch4];
    	motor[backRight] = - vexRT[AccelY] - vexRT[AccelX] + vexRT[Ch4];
    	motor[frontLeft] = - vexRT[AccelY] + vexRT[AccelX] + vexRT[Ch4];
    	motor[backLeft] = - vexRT[AccelY] + vexRT[AccelX] - vexRT[Ch4];

    	/* mobile goal lift */
  		if(vexRT[Btn5D] == 1){motor[goal] = -127;}
    	else if(vexRT[Btn5U] == 1){motor[goal] = 127;}
    	else{motor[goal] = 0;}

    	/* left side cone lift */
    	if(vexRT[Btn7U] == 1){motor[coneLeft] = -127;}
    	else if(vexRT[Btn7D] == 1){motor[coneLeft] = 127;}
    	else{motor[coneLeft] = 0;}
    }
}
